### ISSUE TITLE
Nice handling of errors and display for the user when scryfall can't find the cards

### ISSUE THREAD

**Issue by Shadesfear** [ericjaychi/tigrex#35]
When trying to get price from a card and the user spell's the card in the wrong way, the python error is just returned to the user, this is not a nice user experience. 

Input: 
`tigrex price tarm`

This returns the following: 

Traceback (most recent call last):
  File "/home/chris/.local/bin/tigrex", line 10, in <module>
    sys.exit(main())
  File "/home/chris/.local/lib/python2.7/site-packages/tigrex/__main__.py", line 183, in main
    fire.Fire(Card)
  File "/home/chris/.local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/chris/.local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/chris/.local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/chris/.local/lib/python2.7/site-packages/tigrex/__main__.py", line 49, in price
    card_layout = Card.__get_card_layout(response)
  File "/home/chris/.local/lib/python2.7/site-packages/tigrex/__main__.py", line 103, in __get_card_layout
    return response.json()[LAYOUT]
KeyError: 'layout'

Would be great with a nice message to the user and a way to fix the input error

**Comment by Shadesfear** [comment]
Similar issue is already open, will close
